version: "3.3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "tmp/pids/server.pid && bundle exec rails server --port 3000 --bind '0.0.0.0'"
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
